name: Cleanup Old Versions
on:
  workflow_dispatch:
  schedule:
    - cron: "10 * * * *"
jobs:
  cleanup:
    name: "${{ matrix.package }} cleanup"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - yolks
          - games
          - installers
          - steamcmd
          - java
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: "${{ matrix.package }}"
          package-type: "container"
          min-versions-to-keep: 100
          delete-only-untagged-versions: "true"
          token: ${{ secrets.token }}
