name: build elixir
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - elixir/**
jobs:
  push:
    name: "yolks:elixir_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - leastrio
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          # Use the previous version of buildx https://github.com/docker/buildx/releases
          # to solve https://github.com/docker/build-push-action/issues/761
          version: "0.10.6"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./elixir
          file: ./elixir/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/egomaw/yolks:elixir_${{ matrix.tag }}
