name: build java
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - java/**
jobs:
  push:
    name: "yolks:java_${{ matrix.jdk }}_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - temurin
        - zulu
        - openjdk
        tag:
          - 8
          - 8-forge
#          - 8j9
          - 11
          - 11-forge
#          - 11j9
          - 16
#          - 16j9
          - 17
          - 20
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: "./java/${{ matrix.jdk }}/${{ matrix.tag }}/Dockerfile"

      - uses: docker/setup-qemu-action@v2
        if:  ${{ steps.check_files.outputs.files_exists == 'true' }}

      - uses: docker/setup-buildx-action@v2
        if:  ${{ steps.check_files.outputs.files_exists == 'true' }}
        with:
          version: "latest"
          buildkitd-flags: --debug

      - uses: docker/login-action@v2
        if:  ${{ steps.check_files.outputs.files_exists == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        if:  ${{ steps.check_files.outputs.files_exists == 'true' }}
        with:
          context: ./java
          file: ./java/${{ matrix.jdk }}/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/egomaw/yolks:java_${{ matrix.jdk }}_${{ matrix.tag }}