name: build java
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - java/**
jobs:
  push:
    name: "java:${{ matrix.jdk }}_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - temurin
        - zulu
        - openjdk
        - amazoncorretto
        - graalvm
        tag:
          - '8'
          - '8-forge'
          - '11'
          - '11-forge'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "./java/${{ matrix.jdk }}/${{ matrix.tag }}/Dockerfile"

      - uses: docker/setup-qemu-action@v3
        if:  ${{ steps.check_files.outputs.files_exists == 'true' }}

      - uses: docker/setup-buildx-action@v3
        if:  ${{ steps.check_files.outputs.files_exists == 'true' }}
        with:
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:latest

      - uses: docker/login-action@v3
        if:  ${{ steps.check_files.outputs.files_exists == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        if:  ${{ steps.check_files.outputs.files_exists == 'true' }}
        with:
          context: ./java
          file: ./java/${{ matrix.jdk }}/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/egomaw/java:${{ matrix.jdk }}_${{ matrix.tag }}
